version: '3'
services:
  nginx-proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
     - ./nginx-proxy/default.conf:/etc/nginx/conf.d/default.conf:cached
     - ./nginx-proxy/default.conf:/default.conf:cached
    restart: always
    depends_on:
      - client_app
  client_app:
    build:
      context: ./client
    hostname: client_app
    volumes:
      - ./client:/client:cached
  server_app:
    build:
      context: ./server
    hostname: server_app
    volumes:
      - ./server:/server:cached
      - ./service_key.json:/service_key.json
    environment:
     - SERVICE_KEY=../../service_key.json
      