version: '3'
services:
  nginx-proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
     - ./nginx-proxy/default.conf:/etc/nginx/conf.d/default.conf:cached
     - ./nginx-proxy/default.conf:/default.conf:cached
    restart: always
    depends_on:
      - client_app
  client_app:
    hostname: client_app
    image: danielmooncloud/client:dev
    volumes:
      - ./client:/client:cached
  server_app:
    hostname: server_app
    image: danielmooncloud/server:dev
    volumes:
      - ./server:/server:cached
    environment:
      - SERVICE_KEY_PATH=./service_key.json

      